name: Release

on:
  workflow_dispatch:  
    inputs:
      version:
        description: 'Release version (e.g., v0.1.0)'
        required: false
        default: 'latest'

jobs:
  release:
    runs-on: ubuntu-22.04
    if: github.repository == 'orangeH25/ascend-dra-driver'
    env:
      IMAGE_NAME: ascend-dra-driver
      REGISTRY: docker.io/orangeH25
      VERSION: ${{ github.event.inputs.version || format('manual-{0}', github.run_id) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          chmod +x demo/build-driver.sh
          DRIVER_IMAGE_TAG=${VERSION} ./demo/build-driver.sh
          docker tag registry.example.com/${IMAGE_NAME}:v0.1.0 ${REGISTRY}/${IMAGE_NAME}:${VERSION}	

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${REGISTRY}/${IMAGE_NAME}:${VERSION}
          
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.2

      - name: Prepare Helm values.yaml
        run: |
          mkdir -p tmp-helm
          cp deployments/helm/ascend-dra-driver/values.yaml tmp-helm/values.yaml
          sed -i "s|repository: .*|repository: ${REGISTRY}/${IMAGE_NAME}|g" tmp-helm/values.yaml
          sed -i "s|tag: .*|tag: ${VERSION}|g" tmp-helm/values.yaml

      - name: Package Helm chart
        run: |
          mkdir -p package
          helm package deployments/helm/ascend-dra-driver \
            -f tmp-helm/values.yaml \
            -d ./package
          mv ./package/ascend-dra-driver-*.tgz ./package/ascend-dra-driver-${VERSION}.tgz
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update install.sh with release version
        run: |
          VERSION=${{ env.VERSION }}
          sed -i "s|releases/download/.*/install.sh|releases/download/${VERSION}/install.sh|g" install.sh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            package/ascend-dra-driver-${{ env.VERSION }}.tgz
            install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
